### ISSUE TITLE
Error update_tag 

### ISSUE THREAD

**Issue by bouziane-meed** [googleapis/python-datacatalog#458] opened 2023-01-24 15:17 UTC
I get this error when I run thr update_tag function in purpose to udate the metadata in the datacatalog.

## This is my script :
```python 
........ 

tag = datacatalog_v1.Tag(
            name=f"table_{table_id}_tag",
            template=tag_template.name
        )

# add values in Sheets to tag
for column_name in df:
    tag.fields[column_name] = datacatalog_v1.types.TagField()
    tag.fields[column_name].string_value = df[column_name][index]

try:
    tag_created = datacatalog_client.create_tag(
        parent=table_entry.name,
        tag=tag
    )
    print(f"Created tag: {tag.name}")

except AlreadyExists:
    # Create a client
    request = datacatalog_v1.UpdateTagRequest(
        tag=tag,
    )
    # Make the request
    response = datacatalog_client.update_tag(request=request)
    # Handle the response
    print(f"Tag {tag.name} was Updated ")
    ...........
```

## the error I got :

```
E0124 16:13:49.199000000 17140 src/core/ext/transport/chttp2/transport/hpack_parser.cc:1218] Error parsing metadata: error=invalid value key=content-type value=text/html; charset=UTF-8

```

and it is the result of :     response = datacatalog_client.update_tag(request=request)

**Comment by parthea** [comment] 2023-04-17 14:29
The stack trace looks the same as the one in https://github.com/googleapis/gapic-generator-python/issues/1650 . You'll need to specify a regional endpoint for this API.  For example,

```
endpoint = "us-west1-datacatalog.googleapis.com"
client_options = {"api_endpoint": endpoint}
datacatalog_client = DataCatalogClient(client_options)
```
instead of

```
datacatalog_client = DataCatalogClient()
```

I'm going to close this issue as a duplicate of https://github.com/googleapis/gapic-generator-python/issues/1650 which tracks improving the code snippets to show that a regional endpoint is required.

**Closed by parthea** 2023-04-17 14:29 UTC
Labels: api: datacatalog
